name: Deploy to Github Pages

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Build
        run: |
          yarn
          NODE_ENV="production" yarn run build
          NODE_ENV="production" yarn run next export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/out
